---
title: "Workout Correctness Prediction"
author: "Ivan Lysiuchenko"
date: "July 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
trainingOriginal <- read.csv("pml-training.csv", na.strings = c("NA", "#DIV/0!"))
testingOriginal <- read.csv("pml-testing.csv", na.strings = c("NA", "#DIV/0!"))


library(dplyr)
trainingOriginal <- mutate(trainingOriginal, cvtd_timestamp = 
                               as.POSIXct(trainingOriginal$cvtd_timestamp, "", "%d/%m/%Y %H:%M"))

#ggpairs(training, upper=list(continuous="points", combo="dot_no_facet"))

selectedColumns <- c()
naProportions <- c()

for (i in 1:ncol(trainingOriginal))
{
    naProp <- sum(is.na(trainingOriginal[, i])) / nrow(trainingOriginal)
    if (naProp < 0.3)
    {
        selectedColumns <- c(selectedColumns, i)
        naProportions <- c(naProportions, naProp)
    }
}

training <- trainingOriginal[, selectedColumns]

training <- training[ , 
                      !(names(training) %in% c(  c("X", "user_name", 
                                                   "raw_timestamp_part_1", "raw_timestamp_part_2",
                                                   "cvtd_timestamp", "new_window", "num_window"),
                                                 grep("^total_accel", names(training), 
                                                      value = TRUE)     ))   ]


```
